"""
Cosmoprimo engine for the Boltzmann code DS-CLASS (Dark Scattering).

Implementation Credits:
- Original DS model implementation in CLASS: Pedro Carrilho
- Integration of DS-CLASS into Cosmoprimo: Karim Carrion
"""
import numpy as np
import scipy.interpolate as interp
from scipy.integrate import odeint

from pyclass import dsclass
from .cosmology import BaseEngine, CosmologyInputError, CosmologyComputationError
from . import classy
from . import utils, constants


class DSClassEngine(classy.ClassEngine):

    """Engine for the Boltzmann code DSCLASS."""

    name = 'dsclass'

    def _set_classy(self, params):
        # 1. Apply Dark Scattering Logic
        # (This ensures the C-code gets the parameters it expects)
        if 'xi_ds' in params:
            # Force dark_scattering flag if not present
            if params.get('dark_scattering', 'no') == 'no':
                params['dark_scattering'] = 'yes'

            # DS-CLASS specific constraints (from your previous attempts)
            # Ensure these don't conflict with what cosmoprimo sets automatically
            params['Omega_Lambda'] = 0.
            params['use_ppf'] = 'yes'
            params['gauge'] = 'Newtonian'

            if 'cs2_fld' not in params:
                params['cs2_fld'] = 1.0

        # 2. Define Internal Engine Wrapper
        # This maps DSCLASS errors to Cosmoprimo errors
        class _ClassEngine(dsclass.ClassEngine):

            def compute(self, tasks):
                try:
                    return super(_ClassEngine, self).compute(tasks)
                except dsclass.ClassInputError as exc:
                    raise CosmologyInputError from exc
                except dsclass.ClassComputationError as exc:
                    raise CosmologyComputationError from exc

        # 3. Initialize the actual Engine
        self.classy = _ClassEngine(params=params)

# Incluiding the growth factor and rate with DS.
class Background(classy.BaseClassBackground, dsclass.Background):
    """DS-Class Background."""

    def __init__(self, engine):
        self.engine = engine
        super(Background, self).__init__(engine)
        if not hasattr(self, '_cache'):
            self._cache = {}

    def _solve_ds_ode(self):
        """Solves the DS growth ODE using the background quantities from CLASS."""

        # ==========================================
        # EXTRACT PARAMS
        # ==========================================
        h = self.h
        w0 = getattr(self, 'w0_fld', -1.0)
        wa = getattr(self, 'wa_fld', 0.0)
        xi = float(self.engine._params.get('xi_ds', 0.0))

        # Get physical CDM density (fallback to Omega0_cdm * h^2 if not in params dict)
        omega_cdm = float(self.engine._params.get('omega_cdm', self.Omega0_cdm * h**2))

        # =====================================
        # EXTRACT BACKGROUND ARRAYS FROM CLASS
        # =====================================
        # Fetch the exact background table generated by CLASS
        bg = self.table()

        a_bg = 1.0 / (1.0 + bg['z'])
        ln_a_bg = np.log(a_bg)
        H_bg = bg['H [1/Mpc]']

        # Safely handle massive neutrinos
        if '(.)rho_ncdm[0]' in bg.dtype.names:
            rho_ncdm = bg['(.)rho_ncdm[0]']
        else:
            rho_ncdm = 0.0

        rho_m_bg = bg['(.)rho_b'] + bg['(.)rho_cdm'] + rho_ncdm
        rho_de_bg = bg['(.)rho_fld']

        Omega_m_bg = rho_m_bg / H_bg**2
        Omega_de_bg = rho_de_bg / H_bg**2

        ln_H_bg = np.log(H_bg)
        dlnH_dlna_bg = np.gradient(ln_H_bg, ln_a_bg)

        ln_a_rev = ln_a_bg[::-1]
        Omega_m_interp = interp.interp1d(ln_a_rev, Omega_m_bg[::-1], kind='cubic', fill_value="extrapolate")
        Omega_de_interp = interp.interp1d(ln_a_rev, Omega_de_bg[::-1], kind='cubic', fill_value="extrapolate")
        H_interp = interp.interp1d(ln_a_rev, H_bg[::-1], kind='cubic', fill_value="extrapolate")
        dlnH_dlna_interp = interp.interp1d(ln_a_rev, dlnH_dlna_bg[::-1], kind='cubic', fill_value="extrapolate")

        H0 = H_interp(0.0)
        Omega_de_0 = Omega_de_interp(0.0)
        Om_m_exact = Omega_m_interp(0.0)

        # ===============================================
        # CALCULATE EFFECTIVE COUPLING (see 2111.13598)
        # ===============================================
        Omega_cdm_val = omega_cdm / h**2
        Rc = Omega_cdm_val / Om_m_exact

        unit_conv = 0.0974655
        A0_raw = unit_conv * h * (1.0 - Om_m_exact) * (1.0 + w0) * xi
        Corr_xi = (xi * Rc) / (1.0 + A0_raw * (1.0 - Rc))

        A_base = unit_conv * h * Omega_de_0 * Corr_xi

        # ============
        # ODE SOLVER
        # ============
        def ode_derivs(y, lna):
            D, Dprime = y
            Om_m = Omega_m_interp(lna)
            dlnH = dlnH_dlna_interp(lna)

            a_current = np.exp(lna)
            w_current = w0 + wa * (1.0 - a_current)

            A_val = A_base * (1.0 + w_current) * (Omega_de_interp(lna) / Omega_de_0) * (H_interp(lna) / H0)

            dDprime = - (2.0 + A_val + dlnH) * Dprime + 1.5 * Om_m * D
            return [Dprime, dDprime]

        # Setup integration bounds
        lna_ini = np.log(1.0 / (1.0 + 100.0))
        lna_arr = np.linspace(lna_ini, 0.0, 500)
        y0 = [np.exp(lna_ini), np.exp(lna_ini)]

        # Integrate
        sol = odeint(ode_derivs, y0, lna_arr)
        D_sol = sol[:, 0]
        Dprime_sol = sol[:, 1]
        f_sol = Dprime_sol / D_sol

        # Interpolate and Cache against z
        z_arr = np.exp(-lna_arr) - 1.0

        self._cache['growth_factor_ds'] = interp.interp1d(z_arr[::-1], D_sol[::-1], kind='cubic', fill_value='extrapolate')
        self._cache['growth_rate_ds'] = interp.interp1d(z_arr[::-1], f_sol[::-1], kind='cubic', fill_value='extrapolate')

    @utils.flatarray(dtype=np.float64)
    def growth_factor(self, z):
        if 'growth_factor_ds' not in self._cache:
            self._solve_ds_ode()
        return self._cache['growth_factor_ds'](z) / self._cache['growth_factor_ds'](0.0)

    @utils.flatarray(dtype=np.float64)
    def growth_rate(self, z):
        if 'growth_rate_ds' not in self._cache:
            self._solve_ds_ode()
        return self._cache['growth_rate_ds'](z)

class Thermodynamics(classy.BaseClassThermodynamics, dsclass.Thermodynamics):
    """DS-Class Thermodynamics."""

class Primordial(classy.BaseClassPrimordial, dsclass.Primordial):
    """DS-Class Primordial."""

class Perturbations(classy.BaseClassPerturbations, dsclass.Perturbations):
    """DS-Class Perturbations."""

class Transfer(classy.BaseClassTransfer, dsclass.Transfer):
    """DS-Class Transfer."""

class Harmonic(classy.BaseClassHarmonic, dsclass.Harmonic):
    """DS-Class Harmonic."""

class Fourier(classy.BaseClassFourier, dsclass.Fourier):
    """DS-Class Fourier."""